// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$$0 from "./apps/decohub.ts";
import * as $$$$$$$$$$$$1 from "./apps/site.ts";
import * as $$$$$$$0 from "./sections/BlogPost.tsx";
import * as $$$$$$$1 from "./sections/BlogPosts.tsx";
import * as $$$$$$$2 from "./sections/Faq.tsx";
import * as $$$$$$$3 from "./sections/Footer.tsx";
import * as $$$$$$$4 from "./sections/Header.tsx";
import * as $$$$$$$5 from "./sections/Hero.tsx";
import * as $$$$$$$6 from "./sections/HeroBackground.tsx";
import * as $$$$$$$7 from "./sections/ImageWithParagraph.tsx";
import * as $$$$$$$8 from "./sections/Logos.tsx";
import * as $$$$$$$9 from "./sections/MainPost.tsx";
import * as $$$$$$$10 from "./sections/Testimonials.tsx";
import * as $$$$$$$11 from "./sections/Theme/Theme.tsx";

const manifest = {
  "sections": {
    "barberblog/sections/BlogPost.tsx": $$$$$$$0,
    "barberblog/sections/BlogPosts.tsx": $$$$$$$1,
    "barberblog/sections/Faq.tsx": $$$$$$$2,
    "barberblog/sections/Footer.tsx": $$$$$$$3,
    "barberblog/sections/Header.tsx": $$$$$$$4,
    "barberblog/sections/Hero.tsx": $$$$$$$5,
    "barberblog/sections/HeroBackground.tsx": $$$$$$$6,
    "barberblog/sections/ImageWithParagraph.tsx": $$$$$$$7,
    "barberblog/sections/Logos.tsx": $$$$$$$8,
    "barberblog/sections/MainPost.tsx": $$$$$$$9,
    "barberblog/sections/Testimonials.tsx": $$$$$$$10,
    "barberblog/sections/Theme/Theme.tsx": $$$$$$$11,
  },
  "apps": {
    "barberblog/apps/decohub.ts": $$$$$$$$$$$$0,
    "barberblog/apps/site.ts": $$$$$$$$$$$$1,
  },
  "name": "barberblog",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
